# Generated by Django 3.0.6 on 2020-05-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_B00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Rec', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Address_1', models.CharField(max_length=100)),
                ('Address_2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip_Code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Insurance_B00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_Rec', models.CharField(max_length=100)),
                ('Address_1', models.CharField(max_length=100)),
                ('Address_2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip_Code', models.IntegerField()),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_B01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_Representative_Rec', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Phone_1', models.IntegerField()),
                ('Phone_2', models.IntegerField()),
                ('eMail_Address', models.CharField(max_length=200)),
                ('Insurance_Rec', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='crud_register.Insurance_B00', verbose_name='Insurance Rec')),
            ],
        ),
    ]
