# Generated by Django 3.0.6 on 2020-05-23 09:42

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance_b00',
            options={'verbose_name': 'Insurance B00'},
        ),
        migrations.AlterModelOptions(
            name='insurance_b01',
            options={'verbose_name': 'Insurance B01'},
        ),
        migrations.RemoveField(
            model_name='insurance_b01',
            name='Phone_1',
        ),
        migrations.RemoveField(
            model_name='insurance_b01',
            name='Phone_2',
        ),
        migrations.AddField(
            model_name='insurance_b01',
            name='phone_1',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='insurance_b01',
            name='phone_2',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='insurance_b01',
            name='Insurance_Rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_register.Insurance_B00', verbose_name='Insurance Rec'),
        ),
    ]
