# Generated by Django 3.0.6 on 2020-05-23 11:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_register', '0002_auto_20200523_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_b00',
            name='Phone',
        ),
        migrations.AddField(
            model_name='insurance_b00',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
