# Generated by Django 3.0.6 on 2020-05-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_register', '0003_auto_20200523_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance_b00',
            options={},
        ),
        migrations.AlterModelOptions(
            name='insurance_b01',
            options={},
        ),
        migrations.AlterField(
            model_name='insurance_b01',
            name='Insurance_Rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_register.Insurance_B00'),
        ),
    ]
