# Generated by Django 3.0.6 on 2020-05-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_register', '0004_auto_20200523_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_b00',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='Address_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='Company_Rec',
            new_name='company_Rec',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='company_b00',
            old_name='Zip_Code',
            new_name='zip_Code',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='Address_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='Insurance_Rec',
            new_name='insurance_Rec',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='insurance_b00',
            old_name='Zip_Code',
            new_name='zip_Code',
        ),
        migrations.RenameField(
            model_name='insurance_b01',
            old_name='First_Name',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='insurance_b01',
            old_name='Insurance_Rec',
            new_name='insurance_Rec',
        ),
        migrations.RenameField(
            model_name='insurance_b01',
            old_name='Insurance_Representative_Rec',
            new_name='insurance_Representative_Rec',
        ),
        migrations.RenameField(
            model_name='insurance_b01',
            old_name='Last_Name',
            new_name='last_Name',
        ),
    ]
