# Generated by Django 3.0.6 on 2020-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_register', '0005_auto_20200523_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_b00',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurance_b00',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurance_b01',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
